name: tests

on:
  push:
    branches: [ master, calendar ]
  pull_request:
    branches: [ master, calendar ]

jobs:
  react-ts-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ls -a
      - run: bash ./../../bash/main.sh react ts eslint
    