name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./bash.sh react noVer
  
  react-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./bash.sh react typescript noVer
  
  react-bs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./bash.sh react bootstrap noVer
  
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./bash.sh eslint noVer
    
  react-ts-bs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./bash/main.sh react ts bs eslint noVer
